# TLS certificate for the platform Gateway
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-gateway-cert
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: platform-gateway-tls
  issuerRef:
    name: platform-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - harbor.platform
    - vault.plaform
    - ml-classifier.platform
---
# Gateway - defines the entry point for all platform traffic
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  gatewayClassName: platform-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        node: Terminate
        certificateRefs:
          - name: platform-gateway-tls
            namespace: envoy-gateway-system

